name: Test

on:  # Trigger the workflow on push or pull request, but only for the master branch
  push:
    branches: [master, "release/*"]
  pull_request:
    branches: [master, "release/*"]

jobs:
  mypy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install mypy
        run: |
          grep mypy requirements/test.txt | xargs -0 pip install
          pip list
          pip install -r requirements.txt
          pip install “.[dev, examples]”
          pip install pre-commit
      - run: mypy --install-types --non-interactive
